/**
 * Ground truth for the retrieval evaluation (PROJECT.md 8.8).
 *
 * The corpus is scripted rather than generated by an LLM so that every answer
 * is known exactly: each question points at the planted messages that answer it,
 * and nothing else counts. That makes the scores a conservative lower bound -
 * a retriever that surfaces a genuinely useful filler message gets no credit.
 *
 * Questions are written the way a teammate would type them into `@bot`, not
 * reverse-engineered from the answers. Their categories exist to test the
 * prediction 8.8 asks to confirm or refute:
 *
 *   identifier  the answer hinges on a rare literal token present in both the
 *               question and the answer - a ticket, host, error code, version or
 *               company name. Predicted to favour keyword search.
 *   paraphrase  question and answer share no content words. Predicted to favour
 *               vector search.
 *   lexical     they share ordinary words, with no rare identifier.
 *
 * Every planted fact also has hand-written near misses in DISTRACTORS: messages
 * on the same topic that do not answer. Without them, vector search would look
 * far better than it is - a probe showed "we should deploy the release on monday
 * morning" scoring 0.66 against "when is the deployment window?", above the real
 * answer at 0.49.
 */

export type RoomKey = 'eng' | 'incidents' | 'product' | 'team';

export const CORPUS_ROOMS: Record<RoomKey, { id: string; name: string }> = {
  eng: { id: 'rag-eng-platform', name: 'eng-platform' },
  incidents: { id: 'rag-incidents', name: 'incidents' },
  product: { id: 'rag-product', name: 'product' },
  team: { id: 'rag-team', name: 'team' },
};

export const CORPUS_PEOPLE = [
  'priya',
  'marcus',
  'elena',
  'sam',
  'jordan',
  'wei',
  'noor',
  'dmitri',
] as const;

export type Person = (typeof CORPUS_PEOPLE)[number];

export interface PlantedMessage {
  key: string;
  room: RoomKey;
  sender: Person;
  body: string;
}

export type QuestionCategory = 'identifier' | 'paraphrase' | 'lexical';

export interface EvalQuestion {
  id: string;
  room: RoomKey;
  category: QuestionCategory;
  question: string;
  /** Keys into PLANTED. Order is irrelevant; all of them count as relevant. */
  relevant: string[];
}

export const PLANTED: PlantedMessage[] = [
  // --- identifier ---
  {
    key: 'inc4471-cause',
    room: 'incidents',
    sender: 'wei',
    body: 'INC-4471 postmortem is up: the TLS cert on edge-lb-03 expired because the auto-renew cron had been failing silently since the vault migration',
  },
  {
    key: 'inc4471-actions',
    room: 'incidents',
    sender: 'sam',
    body: 'action items from INC-4471: alert on cert expiry at 14 days out, and move the renewal job off the old cron host',
  },
  {
    key: 'replica07',
    room: 'incidents',
    sender: 'dmitri',
    body: 'db-replica-07 fell about 40 minutes behind primary, a vacuum was blocked by a long analytics query. killed the query and it caught back up',
  },
  {
    key: 'pg172-owner',
    room: 'eng',
    sender: 'priya',
    body: "marcus is owning the postgres 17.2 cutover, he'll send the runbook before the change freeze",
  },
  {
    key: 'plat2208',
    room: 'eng',
    sender: 'elena',
    body: 'PLAT-2208 is merged, the rate limiter was counting websocket pings as requests. it goes out in the thursday build',
  },
  {
    key: 'equota1043',
    room: 'eng',
    sender: 'jordan',
    body: 'for anyone seeing E_QUOTA_1043: it means the tenant hit the per-minute upload cap, not a storage limit. support keeps confusing the two',
  },
  {
    key: 'northwind-ask',
    room: 'product',
    sender: 'noor',
    body: 'call with Northwind Logistics went well, their main ask is SSO through Okta before they sign the annual contract',
  },
  {
    key: 'kestrel-off',
    room: 'product',
    sender: 'marcus',
    body: 'we turned kestrel_search off in prod, it was doubling p95 on the listing page. elena is profiling it',
  },
  {
    key: 'vantor-renewal',
    room: 'team',
    sender: 'noor',
    body: 'reminder the Vantor Cloud contract auto-renews on March 3rd, finance wants the usage numbers two weeks before that',
  },
  {
    key: 'release4180',
    room: 'eng',
    sender: 'sam',
    body: '4.18.0 changelog draft: bulk export, the new audit log view, and the fix for the timezone bug in scheduled reports',
  },
  {
    key: 'brightwave-contact',
    room: 'product',
    sender: 'jordan',
    body: 'our champion at Brightwave is Tomasz Wierzbicki, loop him in on anything about the renewal',
  },

  // --- paraphrase ---
  {
    key: 'deploy-window',
    room: 'eng',
    sender: 'priya',
    body: 'ok final call: we push to prod tuesday night around 11pm once traffic dips',
  },
  {
    key: 'eu-outage',
    room: 'incidents',
    sender: 'wei',
    body: 'the outage was the CDN config push, a bad geo rule routed all EU traffic to the origin in virginia and it melted',
  },
  {
    key: 'offsite-remote',
    room: 'team',
    sender: 'jordan',
    body: "for folks who can't make it to lisbon, every session will be streamed and we'll ship them the swag box",
  },
  {
    key: 'hiring-mobile',
    room: 'team',
    sender: 'priya',
    body: 'headcount approved for two ios engineers and one android engineer, jordan is running the loop',
  },
  {
    key: 'annual-grandfather',
    room: 'product',
    sender: 'elena',
    body: 'annual subscribers keep the old rate until their renewal comes up',
  },
  {
    key: 'building-shut',
    room: 'team',
    sender: 'noor',
    body: 'heads up the building is shut from the 23rd to the 27th for the elevator work, plan to work from home those days',
  },
  {
    key: 'intrusion-token',
    room: 'incidents',
    sender: 'dmitri',
    body: 'the intrusion came through a leaked personal access token in a public gist, it had repo scope. rotated everything',
  },
  {
    key: 'intrusion-gist',
    room: 'incidents',
    sender: 'wei',
    body: 'forensics confirmed that gist sat public for nine days before anyone noticed',
  },
  {
    key: 'expenses-noor',
    room: 'team',
    sender: 'marcus',
    body: 'noor handles all the receipts and travel claims now that finance moved it in house',
  },
  {
    key: 'ci-slow',
    room: 'eng',
    sender: 'dmitri',
    body: 'ci got way slower because the integration jobs spin up a fresh database container per spec file instead of per run',
  },
  {
    key: 'munich-deal',
    room: 'product',
    sender: 'noor',
    body: 'the munich deal closed this morning, 400 seats',
  },
  {
    key: 'dkim-bounce',
    room: 'incidents',
    sender: 'sam',
    body: 'the confirmation mails were bouncing, our sending domain lost its dkim record during the dns cleanup',
  },
  {
    key: 'aws-spend',
    room: 'eng',
    sender: 'marcus',
    body: "to bring aws spend down we're moving batch jobs to spot instances and deleting orphaned ebs volumes",
  },

  // --- lexical ---
  {
    key: 'scale-price',
    room: 'product',
    sender: 'elena',
    body: 'pricing is locked: the Scale plan goes to $49 per seat from the 1st, existing customers keep the old price for 12 months',
  },
  {
    key: 'offsite-dates',
    room: 'team',
    sender: 'jordan',
    body: 'offsite is confirmed for lisbon, october 14 to 16, flights get booked through the travel portal',
  },
  {
    key: 'oncall-easter',
    room: 'incidents',
    sender: 'wei',
    body: 'on call over the easter weekend: sam as primary and wei as secondary',
  },
  {
    key: 'logo-redesign',
    room: 'product',
    sender: 'marcus',
    body: "decision on the logo redesign: we're keeping the current mark and only refreshing the colour palette",
  },
  {
    key: 'rate-limit-raise',
    room: 'eng',
    sender: 'elena',
    body: 'yes the api rate limit goes from 600 to 1200 requests per minute for enterprise tenants next sprint',
  },
  {
    key: 'review-deadline',
    room: 'team',
    sender: 'priya',
    body: 'performance review self assessments are due friday the 8th, managers have until the 15th',
  },
  {
    key: 'search-index-move',
    room: 'eng',
    sender: 'wei',
    body: 'the search index is moving off elasticsearch onto opensearch, cutover planned for the week of the 20th',
  },
  {
    key: 'mobile-onboarding',
    room: 'product',
    sender: 'jordan',
    body: 'plan for the mobile onboarding flow: cut it from five screens to two and defer notification permissions',
  },
];

export const QUESTIONS: EvalQuestion[] = [
  // identifier
  { id: 'I01', room: 'incidents', category: 'identifier', question: 'What was the root cause of INC-4471?', relevant: ['inc4471-cause', 'inc4471-actions'] },
  { id: 'I02', room: 'incidents', category: 'identifier', question: 'What happened with db-replica-07?', relevant: ['replica07'] },
  { id: 'I03', room: 'eng', category: 'identifier', question: 'Who owns the upgrade to postgres 17.2?', relevant: ['pg172-owner'] },
  { id: 'I04', room: 'eng', category: 'identifier', question: 'Is PLAT-2208 fixed yet?', relevant: ['plat2208'] },
  { id: 'I05', room: 'eng', category: 'identifier', question: 'What does E_QUOTA_1043 mean?', relevant: ['equota1043'] },
  { id: 'I06', room: 'product', category: 'identifier', question: 'What did Northwind Logistics ask for?', relevant: ['northwind-ask'] },
  { id: 'I07', room: 'product', category: 'identifier', question: 'Why was kestrel_search disabled?', relevant: ['kestrel-off'] },
  { id: 'I08', room: 'team', category: 'identifier', question: 'When does the Vantor Cloud contract renew?', relevant: ['vantor-renewal'] },
  { id: 'I09', room: 'eng', category: 'identifier', question: 'What is going into release 4.18.0?', relevant: ['release4180'] },
  { id: 'I10', room: 'product', category: 'identifier', question: 'Who is our contact at Brightwave?', relevant: ['brightwave-contact'] },

  // paraphrase
  { id: 'P01', room: 'eng', category: 'paraphrase', question: 'What time did we agree to ship to production?', relevant: ['deploy-window'] },
  { id: 'P02', room: 'incidents', category: 'paraphrase', question: 'Why did the site go down for European customers?', relevant: ['eu-outage'] },
  { id: 'P03', room: 'team', category: 'paraphrase', question: "Can people who can't travel still join the retreat?", relevant: ['offsite-remote'] },
  { id: 'P04', room: 'team', category: 'paraphrase', question: 'Are we hiring anyone for the phone apps?', relevant: ['hiring-mobile'] },
  { id: 'P05', room: 'product', category: 'paraphrase', question: 'What happens to customers who pay yearly?', relevant: ['annual-grandfather'] },
  { id: 'P06', room: 'team', category: 'paraphrase', question: 'Is the office closed at some point soon?', relevant: ['building-shut'] },
  { id: 'P07', room: 'incidents', category: 'paraphrase', question: 'How did the attacker get in?', relevant: ['intrusion-token', 'intrusion-gist'] },
  { id: 'P08', room: 'team', category: 'paraphrase', question: 'Who should I talk to about getting reimbursed?', relevant: ['expenses-noor'] },
  { id: 'P09', room: 'eng', category: 'paraphrase', question: 'Why is the test pipeline taking so long?', relevant: ['ci-slow'] },
  { id: 'P10', room: 'product', category: 'paraphrase', question: 'Did the big German customer sign?', relevant: ['munich-deal'] },
  { id: 'P11', room: 'incidents', category: 'paraphrase', question: "Why can't new users verify their email?", relevant: ['dkim-bounce'] },
  { id: 'P12', room: 'eng', category: 'paraphrase', question: 'What are we doing to cut the cloud bill?', relevant: ['aws-spend'] },

  // lexical
  { id: 'L01', room: 'product', category: 'lexical', question: 'What is the new price for the Scale plan?', relevant: ['scale-price'] },
  { id: 'L02', room: 'team', category: 'lexical', question: 'When is the offsite?', relevant: ['offsite-dates'] },
  { id: 'L03', room: 'incidents', category: 'lexical', question: 'Who is on call over the easter weekend?', relevant: ['oncall-easter'] },
  { id: 'L04', room: 'product', category: 'lexical', question: 'Where did we land on the logo redesign?', relevant: ['logo-redesign'] },
  { id: 'L05', room: 'eng', category: 'lexical', question: 'Is the api rate limit being raised?', relevant: ['rate-limit-raise'] },
  { id: 'L06', room: 'team', category: 'lexical', question: 'When are performance review self assessments due?', relevant: ['review-deadline'] },
  { id: 'L07', room: 'eng', category: 'lexical', question: 'Where is the search index moving to?', relevant: ['search-index-move'] },
  { id: 'L08', room: 'product', category: 'lexical', question: 'What is the plan for the mobile onboarding flow?', relevant: ['mobile-onboarding'] },
];

/**
 * Near misses: same topic, wrong answer. These are what make retrieval hard,
 * and they are never counted as relevant.
 */
export const DISTRACTORS: Omit<PlantedMessage, 'key'>[] = [
  { room: 'incidents', sender: 'sam', body: 'INC-4468 was just a noisy alert, closing it out' },
  { room: 'incidents', sender: 'wei', body: 'INC-4502 postmortem: kafka consumer lag after the broker restart' },
  { room: 'incidents', sender: 'dmitri', body: 'is INC-4417 related to the load balancer cert stuff or separate' },
  { room: 'incidents', sender: 'sam', body: 'db-replica-02 is back in rotation after the kernel patch' },
  { room: 'incidents', sender: 'dmitri', body: 'db-replica-05 disk is at 81 percent, can someone look before it pages' },
  { room: 'eng', sender: 'marcus', body: 'postgres 16.4 patch release is out, low priority for us' },
  { room: 'eng', sender: 'priya', body: 'the analytics box stays on postgres 16 until Q1' },
  { room: 'eng', sender: 'elena', body: 'PLAT-2207 is a duplicate of the websocket reconnect bug' },
  { room: 'eng', sender: 'jordan', body: 'PLAT-2280 needs a repro before anyone picks it up' },
  { room: 'eng', sender: 'jordan', body: 'E_QUOTA_1044 is the storage one, that is the actual disk limit' },
  { room: 'product', sender: 'noor', body: 'Northwind Traders is a different company, please do not mix them up in the CRM' },
  { room: 'product', sender: 'elena', body: 'kestrel_search v2 design doc is in the shared drive' },
  { room: 'team', sender: 'noor', body: 'the Vantor Cloud support ticket about egress fees is still open' },
  { room: 'eng', sender: 'sam', body: '4.17.3 hotfix is out for the export crash' },
  { room: 'eng', sender: 'sam', body: '4.19.0 will be the release with the new dashboard' },
  { room: 'product', sender: 'jordan', body: "Brightwave's security questionnaire came back with a few gaps" },
  { room: 'eng', sender: 'marcus', body: 'we should deploy the release on monday morning instead' },
  { room: 'eng', sender: 'priya', body: 'the prod push for the billing service slipped to thursday' },
  { room: 'eng', sender: 'dmitri', body: 'can we please stop deploying on friday afternoons' },
  { room: 'incidents', sender: 'sam', body: 'the us-east latency blip on monday was a noisy neighbour, not us' },
  { room: 'team', sender: 'jordan', body: 'the offsite hotel block closes on the 1st so book soon' },
  { room: 'team', sender: 'priya', body: 'we are also backfilling one senior frontend role, but that one is web' },
  { room: 'product', sender: 'elena', body: 'monthly plans switch to the new price straight away' },
  { room: 'team', sender: 'noor', body: 'the kitchen on floor 3 is closed for cleaning today' },
  { room: 'incidents', sender: 'wei', body: 'reminder to turn on 2fa for your github account' },
  { room: 'team', sender: 'marcus', body: 'the travel portal is down, book flights directly and keep your receipts' },
  { room: 'eng', sender: 'dmitri', body: 'the unit tests are flaky on the windows runners again' },
  { room: 'product', sender: 'noor', body: 'the paris pilot got pushed to next quarter' },
  { room: 'incidents', sender: 'sam', body: 'password reset mails are fine, it is only the signup ones failing' },
  { room: 'eng', sender: 'marcus', body: 'gcp credits expire in june, use them for the ml experiments' },
  { room: 'product', sender: 'elena', body: 'the Starter plan price is not changing' },
  { room: 'team', sender: 'jordan', body: "last year's offsite was in porto and it rained the whole time" },
  { room: 'incidents', sender: 'wei', body: 'on call this weekend is marcus with dmitri as backup' },
  { room: 'product', sender: 'marcus', body: 'the new website illustrations are in review' },
  { room: 'eng', sender: 'elena', body: 'rate limit dashboards are broken in grafana' },
  { room: 'team', sender: 'priya', body: 'peer feedback forms open next monday' },
  { room: 'eng', sender: 'wei', body: 'search relevance tuning is paused until after the index move' },
  { room: 'product', sender: 'jordan', body: 'the desktop onboarding flow is unchanged for now' },
];

/**
 * Terms that anchor a planted answer. Generated filler must never contain one,
 * or it could become an unlabelled correct answer and corrupt the ground truth.
 * Enforced by a test.
 */
export const FILLER_FORBIDDEN = [
  'inc-4471',
  'edge-lb-03',
  'db-replica-07',
  '17.2',
  'plat-2208',
  'e_quota_1043',
  'northwind',
  'kestrel',
  'vantor',
  '4.18.0',
  'brightwave',
  'wierzbicki',
  '11pm',
  'geo rule',
  'lisbon',
  'swag',
  'ios engineer',
  'android',
  'grandfather',
  'annual subscriber',
  'elevator',
  'personal access token',
  'gist',
  'reimburs',
  'container per spec',
  'munich',
  'dkim',
  'spot instance',
  'ebs',
  'scale plan',
  'easter',
  'logo',
  'opensearch',
  'onboarding flow',
  'self assessment',
  'rate limit goes',
];
